---
- name: Create VM on vSphere
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
    template: "{{ vm_template }}"
    cluster: "{{ vcenter_cluster }}"
    networks:
      - name: "{{ vm_network }}"
    hardware:
      memory_mb: "{{ vm_memory }}"
      num_cpus: "{{ vm_cpu }}"
    disk:
      - size_gb: "{{ vm_disk }}"
        type: thin
  delegate_to: localhost