---
- name: Setup oc-tools host
  hosts: oc_tools
  become: true
  roles:
    - create-vsphere-vm
    - configure-networking
    - install-openshift-tools
    - install-dnf-tools
    - install-foss-tools
    - configure-firewall
    - configure-storage